version: "3.8"

services:
    api:
        build: .
        ports: 
            - 8000:80
        environment: 
            - AUTH_API_PATH=${AUTH_API_PATH}
            - USERS_API_PATH=${USERS_API_PATH}
            - USERS_API_KEY=${USERS_API_KEY}
            - AUTH_API_KEY=${AUTH_API_KEY}
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - SMTP_SERVER=${SMTP_SERVER}
            - SMTP_SERVER_PORT=${SMTP_SERVER_PORT}
            - SMTP_SERVER_USER=${SMTP_SERVER_USER}
            - SMTP_SERVER_PASSWORD=${SMTP_SERVER_PASSWORD}
            - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
        depends_on:
            - db
    db:
        image: mongo
        ports:
            - 27017:27017
    